new member created from register and password hidden
WildCodeSchool-2024-02/LILLE-0224-P3-G2-streetart pull request #28
Opened 2024-06-20 12:34 UTC by audreybaudry

Create road to add a new member

2024-06-20 12:40 UTC, eloregnier approved these changes

2024-06-20 13:25 UTC, fantinerudent requested changes

2024-06-20 13:25 UTC, fantinerudent commented on client/src/pages/Register.jsx
> +    setPwdVisibile(!pwdVisibile);
Visible*

2024-06-20 15:14 UTC, audreybaudry commented on client/src/pages/Register.jsx
> +    setPwdVisibile(!pwdVisibile);
Merci

2024-06-21 08:00 UTC, fantinerudent approved these changes

2024-06-21 08:13 UTC, merged