F25 banned
WildCodeSchool-2024-02/LILLE-0224-P3-G2-streetart pull request #60
Opened 2024-07-09 09:40 UTC by iSayZ

2024-07-09 10:03 UTC, audreybaudry approved these changes

2024-07-09 12:22 UTC, fantinerudent requested changes

2024-07-09 12:22 UTC, fantinerudent commented on server/database/models/AccountRepository.js
> +      // COMMENT RÉCUPÉRER L'OPÉRATION ET DONC L'ID DE L'ACCOUNT À L'ORIGINE DU SIGNALEMENT ?????
only comments in french??

2024-07-09 18:31 UTC, iSayZ commented on server/database/models/AccountRepository.js
> +      // COMMENT RÉCUPÉRER L'OPÉRATION ET DONC L'ID DE L'ACCOUNT À L'ORIGINE DU SIGNALEMENT ?????
It's OK

2024-07-10 13:11 UTC, fantinerudent approved these changes

2024-07-10 15:12 UTC, merged